# Generated by Django 5.2.8 on 2026-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_hostel_warden_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='sharing_type',
            field=models.IntegerField(default=1, help_text='Number of students allowed per room'),
        ),
    ]
