# Generated by Django 5.2.8 on 2026-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_complaint_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='warden_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
